### ISSUE TITLE
Supporting Pug templates

### ISSUE THREAD

**Issue by aksenovdev** [jsverse/transloco-keys-manager#14]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Keys extracted only from .ts and .html files

## Expected behavior

Keys extracted from files specified by the user

## What is the motivation / use case for changing the behavior?

In our project we use pug and earlier I can extract keys with help [ngx-translate-extract](https://github.com/biesbjerg/ngx-translate-extract) from any files with using --pattern flag (for example --patterns /**/*.{pug,ts,js}).

Have you any plans about this?

**Comment by NetanelBasal** [comment]
We'd love to see a PR. It should be straightforward.
