### ISSUE TITLE
Feature: Add config for newline at the end of generated JSONs

### ISSUE THREAD

**Issue by CapoD** [jsverse/transloco-keys-manager#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

JSON files created by `transloco-keys-manager extract` do not have new lines at the end which collides with Unix best practices (e.g. [Why Should Text Files End With a Newline in Linux](https://www.baeldung.com/linux/files-end-with-newlines)).
 

### Describe the solution you'd like

Add a configuration parameter to add new lines at JSON EOF.

### Describe alternatives you've considered

```markdown
ignore the topic 🥺
always add new lines to the EOF which might create legacy problems
```

### Describe alternatives you've considered

always add new lines to the EOF which might create legacy problems

### I would like to make a pull request for this feature

Yes 🚀

**Comment by Redunca** [comment]
I face the same issue, for now I have edited my `package.json` file to run `extract` then `prettier`
It's an ugly workaround that prevent our Pull Requests tu be bloqued by invalid formatting on the translation files

**Comment by Redunca** [comment]
> I think that the keys manager should just run prettier at the end of the process instead of the specific option of a new line at EOF. WDYT?

I agree with you, I don't think that loading the tool with too much options is a good idea. Maybe in the configuration, give the formatting tool that will be used, so all the configuration about formatting is managed by it instead of the keys-manager ?

**Comment by shaharkazaz** [comment]
@Redunca have you got any other tools that allow this option I can use as a reference? What are you using for formatting?

**Comment by shaharkazaz** [comment]
@CapoD @Redunca Can you share what tools you are using?

**Comment by CapoD** [comment]
@shaharkazaz We are using Prettier and / with NX.

**Comment by shaharkazaz** [comment]
@CapoD The keys manager is running prettier on the resulting files, and as far as I know, it should append an empty line, can you elaborate on why that's not the case for you?

**Comment by CapoD** [comment]
I will look into it. Maybe we were using the old keys manager when I commented the issue, since it took us a while to learn that the transloco packages have been renamed / moved to jsverse

**Comment by shaharkazaz** [comment]
Thanks for the input, if you have any suggestions to how to make it clearer I'd be happy to hear 🙂

**Comment by CapoD** [comment]
@shaharkazaz I checked it out and it was indeed the old keys manager. 
Unfortunately, I have no suggestions that would make it clearer.

Thanks for your effort and your great work with Transloco. 

Stay safe!
