### ISSUE TITLE
Feature: clarify emitErrorOnExtraKeys in docs

### ISSUE THREAD

**Issue by mackelito** [jsverse/transloco-keys-manager#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

we have `emitErrorOnExtraKeys: Emit an error and exit the process if extra keys were found (default is false)` in the readMe but what does it mean.. what is a "extra key"? 😁

### Describe alternatives you've considered

```markdown
N/A
```

### Describe alternatives you've considered

N/A

### I would like to make a pull request for this feature

Yes 🚀

**Comment by shaharkazaz** [comment]
It's a completing option to `removeExtraKeys`, extra keys are keys that exist in your translations but are not used in your code.

**Comment by shaharkazaz** [comment]
@mackelito Would you like to make a PR for this?
