### ISSUE TITLE
Bug: transloco-keys-manager find cannot process files with new control flow (angular 17)

### ISSUE THREAD

**Issue by lkuendig** [jsverse/transloco-keys-manager#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a regression?

No

### Current behavior

[Angular v17](https://blog.angular.io/introducing-angular-v17-4d7033312e4b) introduces a new built-in control flow syntax that isn't recognized by the `transloco-keys-manager find` method.

### Expected behavior

```
@if (a > b) {
  {{ t('a') }}
}
```
shoud not be handled as missing key.

as soon as the new control flow is added to a file, the entire file is processed wrongly (all keys are ignored) and not just the part in the new control flow. my guess is the code crashes with the new syntax but could not locate the issue in the code

### Please provide a link to a minimal reproduction of the bug

N/A

### Please provide the environment you discovered this bug in

```markdown
Transloco: 6.0.4
Transloco Keys Manager: 3.8.0
Angular: 17.3.4
Node: 20.10.0
Package Manager: npm 10.2.3
OS: Windows 10 (22H2)
```

### I would like to make a pull request for this bug

No

**Comment by shaharkazaz** [comment]
@lkuendig you are not using the latest version.
Please update your dependency to `@jsverse/transloco-keys-manager`
