### ISSUE TITLE
Bug: find gets stuck

### ISSUE THREAD

**Issue by petrakristova** [jsverse/transloco-keys-manager#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a regression?

No

### Current behavior

When running `transloco-keys-manager find`, it starts to do something but it always gets stuck at this point for a very long time:

![image](https://github.com/jsverse/transloco-keys-manager/assets/64610674/80d60f42-3bb7-495e-8c4b-debfbcd1fcdc)

It's not even possible to kill it with `Ctrl+c` in terminal (tried in windows powershell, windows command prompt).

This worked well for us, the behavior came after we updated from:
- "@ngneat/transloco": "^6.0.4" -> "@jsverse/transloco": "^7.4.1"
- "@ngneat/transloco-keys-manager": "^3.8.0" -> "@jsverse/transloco-keys-manager": "^4.2.0"

### Expected behavior

It shouldn't get stuck for so long and it should be possible to kill the process.

### Please provide a link to a minimal reproduction of the bug

No link, this should be hopefully reproducible easily.

### Please provide the environment you discovered this bug in

```markdown
Transloco: 7.4.1
Transloco Keys Manager: 4.2.0
Angular: 17.3.9
Node: 20.14.0
Package Manager: yarn 4.2.2
OS: win32 x64
```

### Additional context

- we have scopes provided by `TRANSLOCO_SCOPE` for modules in our app
- we don't have every language for every scope defined yet - e.g. we have more languages (en-US.json, de-DE.json, es-ES.json) for root scope (directly in assets/i18n folder) but we currently have only fallback language (en-US.json) in some of the scopes (e.g. in assets/i18n/firstScope, assets/i18n/anotherScope folders)

### I would like to make a pull request for this bug

No

**Comment by MikeDabrowski** [comment]
It seems to be getting stuck here

https://github.com/jsverse/transloco-keys-manager/blob/22a5731b2132acf1bf36b2f7543b683e06732488/src/keys-detective/build-table.ts#L68

**Comment by shaharkazaz** [comment]
@petrakristova it should be ok in `v4.2.2`, thanks @MikeDabrowski

**Comment by petrakristova** [comment]
Great! Thank you very much for solving this so quickly, I really appreciate it 🙂
