### ISSUE TITLE
Bug: find doesn't consider 'prefix'

### ISSUE THREAD

**Issue by MikeDabrowski** [jsverse/transloco-keys-manager#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a regression?

Yes

### Current behavior

When running `find` and having the code migrated to latest transloco version, which uses prefix instead read, the find does not use those prefixes. As if it still looks for 'read' instead. 

![image](https://github.com/jsverse/transloco-keys-manager/assets/17836911/f81c990d-bf8f-4959-b8e0-c4827d2afba6)

### Expected behavior

In transloco docs it is written that read will be deprecated in v8 but since it encourages prefix I think the find should support both for the time being.

### Please provide a link to a minimal reproduction of the bug

[Last commit](https://github.com/MikeDabrowski/transloco-find-read-prefix-bug/commit/6b7bbc997b3a2bae70e88f2b6ed88386dd90a94b)
Also initial commit has its own bug

### Please provide the environment you discovered this bug in

```markdown
"@jsverse/transloco": "^7.4.2",
"@jsverse/transloco-locale": "^7.0.1",
"@jsverse/transloco-messageformat": "^7.0.1",
"@angular/cli": "^17.3.8",
Node: v21.0.0
Package Manager: npm
OS: windows
```

### I would like to make a pull request for this bug

Yes 🚀

**Comment by shaharkazaz** [comment]
Merged 👍
