### ISSUE TITLE
Detect keys from typescript files from extended TranslocoService

### ISSUE THREAD

**Issue by tomaslaw94** [jsverse/transloco-keys-manager#28]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

`transloco-keys-manager find` does not detect keys in typescript file unless used specifically by `TranslocoService`

## Expected behavior

`transloco-keys-manager find` should detect keys in typescript file if used by either `TranslocoService` or an extended `TranslocoService`

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## What is the motivation / use case for changing the behavior?

The main motivation is to allow extending TranslocoService to each project specific needs.

A simple use case would be:

Want to manually load translations for the current scope and current language. So, I'm abstracting all the logic from TranslocoService for getting langChanges$ observable and calling the load() method into a single method (e.g. `loadScopedTranslations(scope: string)`).

This way, I just need to call this method in the components I need.

## Environment

<pre><code>
Angular version: 9.0.4

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.15.3 
- Platform: Windows 

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
@tomaslaw94 You are welcome to open a PR for it 🙂

**Comment by ippeiukai** [comment]
📝 I'm considering of abstracting (or wrapping) transloco with our own code as well.

It would be a nice if one can customize what usage gets extracted. Something like this in Lingui:
https://lingui.dev/ref/conf#runtimeconfigmodule

I had a quick scan over the extractors what values are hardcoded:
- typescript
  - marker
    - import path: `@jsverse/transloco-keys-manager`, `@ngneat/transloco-keys-manager`
  - pure-function
    - identifier: `translate`
  - service
    - identifier: `TranslocoService`
- template
  - comments
    - directive selector (attribute or structural): `transloco`
    - identifier: getConfig().marker (defaults to `t`)
  - directive
    - directive selector (attribute or structural): `transloco`
  - pipe
    - pipe name: `transloco`
  - structural-directive
    - directive selector (attribute or structural): `transloco`
    - directive input: `translocoPrefix`, `translocoRead`
