### ISSUE TITLE
Feature: config file in typescript

### ISSUE THREAD

**Issue by baxyz** [jsverse/transloco-keys-manager#78]
The config file name proposed is in javascript `transloco.config.js` and other formats are supported according [this doc](https://github.com/davidtheclark/cosmiconfig/#cosmiconfig), including YML, but not yet typescript.

It should be very convenient allowing a config file formatting in typescript.

The library used, `cosmiconfig`, is supposed already supporting the TS extension according the [davidtheclark/cosmiconfig#122](https://github.com/davidtheclark/cosmiconfig/issues/122#issuecomment-386813707) issue.

Could we add this feature?

### Contribution
I want to make a pull request for this feature:
- [ ] Yes! 🚀
- [x] Maybe next time

**Comment by brebaje** [comment]
+1

**Comment by shaharkazaz** [comment]
@baxyz As of [this commit](https://github.com/jsverse/transloco/commit/fc4fc6b73c8707a15671de14c60cc7665c74395e) the schematics creates a `ts` config. 
You can migrate to the format according to [the docs](https://jsverse.github.io/transloco/docs/getting-started/installation#transloco-global-config), just make sure you are using the updated version of `@jsverse/transloco` (for the transloco utils)
